import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import ThemeRegistry from "@/app/theme/ThemeRegistry";
import "./globals.css";
import Header from "@/app/components/common/Header";

const archivo = Archivo({
    subsets: ["latin"],
    variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={archivo.variable}
      >
          <ThemeRegistry>
              <Header/>
              {children}
          </ThemeRegistry>
      </body>
    </html>
  );
}
