spring.application.name=video-api

spring.config.import=optional:file:.env[.properties]
tmdb.api.access.token=${TMDB_API_ACCESS_TOKEN}

video.storage-path=../videos/
video.hls-output-path=../hls_output/
video.segment-duration=10
video.seek-threshold-segments=3

spring.cache.jcache.config=classpath:ehcache.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=${PGSQL_USER}
spring.datasource.password=${PGSQL_PASSWORD}
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml