spring.application.name=video-api

spring.config.import=optional:file:.env[.properties]
tmdb.api.access.token=${TMDB_API_ACCESS_TOKEN}

video.storage-path=../videos/
video.hls-output-path=../hls_output/
video.segment-duration=10
video.seek-threshold-segments=3

spring.cache.jcache.config=classpath:ehcache.xml